#If a brand new machine
#git clone
#aws configure
#install terraform
#terraform init


#It will be ran by github when push the code

name: Terraform-CD

on:
 #push:
 #  branches:
 #    - main
 workflow_dispatch:
  inputs:
   environment:
    description: 'Environment to run tf apply on'
    required: true
    default: "dev"
    type: choice
    options:
    ##these options here can be used to load different blocks of yaml for different steps
    - dev
    - staging
    - prod
        
# declare the running agents
jobs:
 terraform-cd:
   runs-on: ubuntu-latest

#git clone

   steps:
##setup
   - name: Checkout repository
     uses: actions/checkout@v2

#aws configure
   - name: Configure AWS credentials
     uses: aws-actions/configure-aws-credentials@v1
     with:
       aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
       aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
       aws-region: us-east-1

#install terraform
   - name: Set up Terraform
     uses: hashicorp/setup-terraform@v1

   - name: Initialize Terraform
     run: terraform init

#terraform plan
   - name: Terraform Apply
     run: terraform apply --auto-approve
