#If a brand new machine
#git clone
#aws configure
#install terraform
#terraform init


#It will be ran by github when push the code

name: Terraform Init

on:
 pull_request:
   branches:
     - main

# declare the running agents
jobs:
 terraform-ci:
   runs-on: ubuntu-latest

#git clone

   steps:
##setup
   - name: Checkout repository
     uses: actions/checkout@v2


#aws configure
   - name: Configure AWS credentials
     uses: aws-actions/configure-aws-credentials@v1
     with:
       aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
       aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
       aws-region: us-east-1

#install terraform
   - name: Set up Terraform
     uses: hashicorp/setup-terraform@v1

   - name: Terraform Lint
     run: terraform fmt -recursive

   - name: Initialize Terraform
     run: terraform init

   - name: Terraform Validate
     run: terraform validate -no-color

#terraform plan
   - name: Terraform Plan
     run: terraform plan
